package MIDI::Simple::Drummer::API;
our $VERSION = '0.00_02';
1;
__END__

=head1 NAME

MIDI::Simple::Drummer::API - DIY Beats

=head1 DESCRIPTION

How to build your own drummer...

For the most part, the essential methods are already documented in
L<MIDI::Simple::Drummer>.  This document is about extending the
capabilities of our drummer and is (obviously) incomplete.

=head1 OPTIONS

=head2 kit

Set instrumentation.

=head2 style

Define patterns.

=head2 dynamics

Define nuance methods.

=head1 TO DO

Flesh-out this document!

=head1 SEE ALSO

Style package(s) like L<MIDI::Simple::Drummer::Rock>.

=head1 AUTHOR AND COPYRIGHT

Gene Boggs E<lt>gene@cpan.orgE<gt>

Copyright 2010, Gene Boggs, All Rights Reserved.

=head1 LICENSE

This program is free software; you can redistribute or modify it under
the same terms as Perl itself.

=cut
