=head1 NAME

MIDI::Simple::Drummer::API - DIY Beats

=head1 DESCRIPTION

How to build your own drummer...

=head1 CLASS METHODS

For the most part, the essential methods are already documented in
L<MIDI::Simple::Drummer>, itself, but this document is about extending
the capabilities of our drummer.

=head2 patterns()

Style

=head2 accent()

Nuance

=head2 kit()

Instrumentation

=head2 backbeat()

Try useing alternate patches!

=head2 TO DO

Flesh-out this doc!

=head1 SEE ALSO

Style package(s) like L<MIDI::Simple::Drummer::Rock>.

=head1 AUTHOR AND COPYRIGHT

Gene Boggs E<lt>gene@cpan.orgE<gt>

Copyright 2010, Gene Boggs, All Rights Reserved.

=head1 LICENSE

This program is free software; you can redistribute or modify it under
the same terms as Perl itself.

=cut
