#!/usr/bin/perl
use strict;
use warnings;
use MIDI::Simple::Drummer;
my $d = MIDI::Simple::Drummer->new();
use Data::Dumper;print Data::Dumper->new([
#    $d->phrases, $d->beats,
#    scalar $d->snare, scalar $d->kick, scalar $d->tick,
#    scalar $d->kicktick, scalar $d->backbeat,
#    $d->kit,
#    scalar $d->kit('kick'),
#    $d->kick,
#    $d->name_of('kick'),
    $d->_p2n,
#    $d->pattern,
#    $d->score,
])->Indent(1)->Terse(1)->Sortkeys(1)->Dump;
