#!/usr/bin/perl
use strict;
use warnings;
use MIDI::Simple::Drummer;
my $d = MIDI::Simple::Drummer->new();
$d->count_in;
use Data::Dumper;local$Data::Dumper::Indent=1;local$Data::Dumper::Terse=1;local$Data::Dumper::Sortkeys=1;
warn Dumper(
#    $d->phrases, $d->beats,
#    scalar $d->snare, scalar $d->kick, scalar $d->tick,
#    scalar $d->kicktick, scalar $d->backbeat,
    $d->kit,
#    $d->_p2n,
#    $d->pattern,
#    $d->score,
);
