#!/usr/bin/perl
use strict;
use warnings;

use MIDI::Simple::Drummer;
my $d = MIDI::Simple::Drummer->new(-bpm => shift || 100);

#use Data::Dumper;local$Data::Dumper::Indent=1;local$Data::Dumper::Terse=1;local$Data::Dumper::Sortkeys=1;
#die Dumper($d->p2n);
$d->count_in();

my $last_fill = 0;

for(0 .. $d->phrases - 1) {
    $d->beat_2(-fill => $_);
    $d->beat_3;
#    if($_ % 2 > 0) {
#        $d->beat_5;
#        $last_fill = $d->fill(-last => $last_fill);
#        $last_fill = $d->fill(-n => 3);
        $last_fill = $d->fill();
warn"last_fill: $last_fill\n";
#    }
#    else {
#        $d->beat_4;
#    }
}
#$d->option_patch();
$d->write;

__END__
  'Acoustic Bass Drum' => '35',
  'Acoustic Snare' => '38',
  'Bass Drum 1' => '36',
  'Cabasa' => '69',
  'Chinese Cymbal' => '52',
  'Claves' => '75',
  'Closed Hi-Hat' => '42',
  'Cowbell' => '56',
  'Crash Cymbal 1' => '49',
  'Crash Cymbal 2' => '57',
  'Electric Snare' => '40',
  'Hand Clap' => '39',
  'Hi Bongo' => '60',
  'Hi Wood Block' => '76',
  'Hi-Mid Tom' => '48',
  'High Agogo' => '67',
  'High Floor Tom' => '43',
  'High Timbale' => '65',
  'High Tom' => '50',
  'Long Guiro' => '74',
  'Long Whistle' => '72',
  'Low Agogo' => '68',
  'Low Bongo' => '61',
  'Low Conga' => '64',
  'Low Floor Tom' => '41',
  'Low Timbale' => '66',
  'Low Tom' => '45',
  'Low Wood Block' => '77',
  'Low-Mid Tom' => '47',
  'Maracas' => '70',
  'Mute Cuica' => '78',
  'Mute Hi Conga' => '62',
  'Mute Triangle' => '80',
  'Open Cuica' => '79',
  'Open Hi Conga' => '63',
  'Open Hi-Hat' => '46',
  'Open Triangle' => '81',
  'Pedal Hi-Hat' => '44',
  'Ride Bell' => '53',
  'Ride Cymbal 1' => '51',
  'Ride Cymbal 2' => '59',
  'Short Guiro' => '73',
  'Short Whistle' => '71',
  'Side Stick' => '37',
  'Splash Cymbal' => '55',
  'Tambourine' => '54',
  'Vibraslap' => '58'
