#!/usr/bin/perl
use strict;
use warnings;
use MIDI::Simple::Drummer;
my $d = MIDI::Simple::Drummer->new(
    -bpm     => shift || 111,
    -volume  => shift || 100,
#    -phrases => shift || 8,
#    -beats   => shift || 3,
);
$d->count_in(2);
for my $p (1 .. $d->phrases) {
    for my $p (1 .. $d->beats) {
        $d->note($d->EIGHTH, $d->rotate_backbeat(-beat => $p));
        $d->note($d->EIGHTH, $d->tick);
#        $d->note($d->EIGHTH, $d->tick);
    }
}
$d->write("$0.mid");
