#!/usr/bin/perl
use strict;
use warnings;
use MIDI::Simple;
use Data::Dumper;
warn Dumper(
[   map {"$_ => $MIDI::Simple::Volume{$_}"}
    sort { $MIDI::Simple::Volume{$a} <=> $MIDI::Simple::Volume{$b} }
    keys %MIDI::Simple::Volume
]
);
